version: '3'
services:

  registry:
    image: eclipsebasyx/aas-registry:1.4.0
    container_name: aas-registry
    environment:
      basyxregistry_registry_backend: MongoDB
      basyxmongodb_dbname: basyx
      basyxdocker_dbcollectioregistry: registry
      basyxcontext_accesscontrolalloworigin: "*"
    ports:
      - ${REGISTRY_PORT}:4000
    links:
      - "mongo-db:mongodb"
    depends_on:
      - mongo-db

  aas-server:
    image: eclipsebasyx/aas-server:1.4.0
    container_name: aas-server
    ports:
      - ${AAS_SERVER_PORT}:4001
    environment:
      basyxaas_aas_backend: MongoDB
      basyxmongodb_dbname: basyx
      basyxdocker_dbcollectionaas: aas
      basyxdocker_dbcollectionsubmodels: submodels
      basyxcontext_accesscontrolalloworigin: "*"
    links:
      - "mongo-db:mongodb"
    depends_on:
      - mongo-db

  aas-gui:
    image: eclipsebasyx/aas-gui:v230403
    ports:
      - "3000:3000"
    environment:
      VITE_REGISTRY_PATH: http://localhost:4000/registry
    depends_on:
      - aas-server
      - registry

  mongo-db:
    image: mongo
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"     # TODO remove before deployment (basyx does not support Mongo authentication, so port forwarding would leave the database unprotected)