version: '3'
services:

  registry:
    image: eclipsebasyx/aas-registry:1.3.0
    container_name: aas-registry
    environment:
      basyxregistry_registry_backend: SQL
      basyxsql_dbuser: postgres
      basyxsql_dbpass: password
      basyxsql_dburl: //basyx-database:5432/
    ports:
      - ${REGISTRY_PORT}:4000

  aas-server:
    image: eclipsebasyx/aas-server:1.3.0
    container_name: aas-server
    ports:
      - ${AAS_SERVER_PORT}:4001

  kgt-application:
    build: .
    container_name: kgt-application
    ports:
      - ${APP_PORT}:8080
      - "5005:5005"

  basyx-database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"