version: '3'
services:

  registry:
    image: eclipsebasyx/aas-registry:1.3.0
    container_name: aas-registry
    environment:
      basyxregistry_registry_backend: MongoDB
      basyxmongodb_dbname:
      basyxdocker_dbconnectionstring: mongodb://mongo-db:27017/
      basyxdocker_dbcollectioregistry:
    ports:
      - ${REGISTRY_PORT}:4000

  aas-server:
    image: eclipsebasyx/aas-server:1.3.0
    container_name: aas-server
    ports:
      - ${AAS_SERVER_PORT}:4001
    environment:
      basyxaas_registry_path:
      basyxaas_aas_backend: MongoDB
      basyxmongodb_dbname:
      basyxdocker_dbconnectionstring: mongodb://mongo-db:27017/
      basyxdocker_dbcollectionaas:
      basyxdocker_dbcollectionsubmodels:

  kgt-application:
    build: .
    container_name: kgt-application
    ports:
      - ${APP_PORT}:8080
      - "5005:5005"

  mongo-db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"