version: '3'
services:

  kgt-application:
    build: .
    container_name: kgt-application
    ports:
      - ${APP_PORT}:8080
      - "5005:5005"
    environment:
      - "basyx.infrastructure.registryServerPath=http://registry:4000/registry/api/v1/registry"
      - "basyx.infrastructure.aasServerPath=http://aas-server:4001/aasServer/shells"
    depends_on:
      - aas-server
      - registry

  registry:
    image: eclipsebasyx/aas-registry:1.4.0
    container_name: aas-registry
    environment:
      basyxregistry_registry_backend: MongoDB
      basyxmongodb_dbname: basyx
      basyxdocker_dbcollectioregistry: registry
      # basyxdocker_dbconnectionstring: mongodb://mongo-db:27017/   # seems to be currently unused. No matter what is set basyx always tries to connect to mongodb:27017
    ports:
      - ${REGISTRY_PORT}:4000
    links:
      - "mongo-db:mongodb"
    depends_on:
      - mongo-db

  aas-server:
    image: eclipsebasyx/aas-server:1.4.0
    container_name: aas-server
    ports:
      - ${AAS_SERVER_PORT}:4001
    environment:
      basyxaas_aas_backend: MongoDB
      basyxmongodb_dbname: basyx
      basyxdocker_dbcollectionaas: aas
      basyxdocker_dbcollectionsubmodels: submodels
      # basyxdocker_dbconnectionstring: mongodb://mongo-db:27017/   # seems to be currently unused. No matter what is set basyx always tries to connect to mongodb:27017
    links:
      - "mongo-db:mongodb"
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"     # TODO remove before deployment (basyx does not support Mongo authentication, so port forwarding would leave the database unprotected)