### upload file
POST http://localhost:8080/api/files
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test.aasx"

< ../src/test/resources/aasx/test.aasx
--WebAppBoundary--


### get files list
GET http://localhost:8080/api/files
Accept: application/json

### get file
GET http://localhost:8080/api/files/test.aasx
Accept: application/json
