### upload file
POST http://localhost:8080/api/files
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test.aasx"

< ../src/test/resources/aasx/02_Bosch.aasx
--WebAppBoundary--


### get files list
GET http://localhost:8080/api/files
Accept: application/json

### get file
GET http://localhost:8080/api/files/37e29d24-47e8-4f18-8b6f-1b5fbc057854
Accept: application/json
